name: CI/CD Pipeline for Assignment NWG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Initialize Terraform
      working-directory: ./terraform-project
      run: terraform init

    - name: Validate Terraform
      working-directory: ./terraform-project
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./terraform-project
      run: terraform plan

    
