name: Python CI/CD Workflow

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out your code

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

      # Step 4: Set up AWS credentials using the secrets
      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'  # Replace with the region you are using
        run: |
          aws sts get-caller-identity  # This command verifies if AWS credentials are set correctly

      # Step 5: Run the Python script
      - name: Run script
        run: |
          python boto_2.py  # Ensure that boto_2.py is in the root of your repository

      # Step 6: Optional Deployment Step (If needed)
      - name: Deploy (optional)
        if: success()
        run: |
          echo "Deploying to production..."  # Replace with your actual deployment command
