name: Python CI Workflow

on:
  push:
    branches:
      - master  # Trigger on push to master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu for the build environment
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python boto_2.py  # Ensure the script is named correctly and exists

      # Step 5: Optional: Any additional steps (like testing or deploying)
