name: Python CI/CD Workflow

on:
  push:
    branches:
      - master  # Trigger on push to master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Python script
        run: |
          python boto_2.py  # Replace with your actual Python script name

      - name: Deploy (optional)
        if: success()  # Only deploy if previous steps worked
        run: |
          echo "Deploying to production..."  # Replace this with your actual deployment steps
